#!/usr/bin/env python3
"""Generate the Rust models and the operation table from the shared API spec.

    python3 tools/generate.py           # write src/models_gen.rs and src/operations_gen.rs
    python3 tools/generate.py --check   # exit 1 if the committed files are out of date

Inputs (from the cexy-api-spec repository, checked out next to this one, or $CEXY_API_SPEC):
  spec/openapi.sdk.json   models, operations, query parameters
  surface.yaml            the allowlist: auth and scope of every operation
  errors.yaml             every error code

Needs Python 3.9+, PyYAML and rustfmt (set $RUSTFMT to use another binary). The output is
deterministic and rustfmt-clean; CI checks both.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SPEC_DIR = Path(os.environ.get("CEXY_API_SPEC", ROOT.parent / "cexy-api-spec"))
MODELS = ROOT / "src" / "models_gen.rs"
OPERATIONS = ROOT / "src" / "operations_gen.rs"
HEADER = "// Code generated by tools/generate.py from cexy-api-spec; DO NOT EDIT.\n\n"

# Schemas written by hand (error.rs, amount.rs) or not needed as Rust types.
SKIP_SCHEMAS = {"ErrorBody", "ErrorResponse", "DetailValue", "Amount"}

# Rust names for API schemas: "...Response" is dropped, except where the bare name is taken.
RENAMES = {
    "PlaceOrderResponse": "PlaceOrderResponse",
    "CancelAllResponse": "CancelAllResult",
    "CancelFailureResponse": "CancelFailure",
    "JoinPoolResponse": "JoinPoolResult",
    "ExitPoolResponse": "ExitPoolResult",
}

# Operations whose query parameters are identical share one params struct.
SHARED_PARAMS = {
    "export_deposits": "ExportParams",
    "export_ledger": "ExportParams",
    "export_orders": "ExportParams",
    "export_trades": "ExportParams",
    "export_withdrawals": "ExportParams",
}

# Error codes the SDK sets itself; the API never sends them (not in errors.yaml).
CLIENT_ERROR_CODES = {
    "UNEXPECTED_REDIRECT": "The server answered with a redirect (3xx). The SDK never follows redirects, so\n"
                           "credentials and orders are never re-sent to another URL. Set by the SDK; the API\n"
                           "never sends it.",
}

RUST_KEYWORDS = {"type", "ref", "match", "mod", "move", "self", "static", "struct", "trait", "use", "where",
                 "loop", "impl", "in", "fn", "for", "enum", "crate", "const", "as", "async", "await", "box",
                 "dyn", "else", "extern", "false", "true", "if", "let", "mut", "pub", "return", "super", "unsafe",
                 "while", "yield", "abstract", "become", "do", "final", "macro", "override", "priv", "typeof",
                 "unsized", "virtual", "try", "gen"}


def pascal(name: str) -> str:
    m = re.fullmatch(r"(\d+)([a-z]+)", name)
    if m:  # "1h" -> "H1", "15m" -> "M15" (identifiers cannot start with a digit)
        return m.group(2).upper() + m.group(1)
    parts = re.split(r"[_\-\s/.]+", name)
    return "".join(p[:1].upper() + p[1:].lower() if p.isupper() else p[:1].upper() + p[1:] for p in parts if p)


def snake(name: str) -> str:
    s = re.sub(r"[\-\s/.]+", "_", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower()
    return f"r#{s}" if s in RUST_KEYWORDS else s


def rust_name(schema: str) -> str:
    if schema in RENAMES:
        return RENAMES[schema]
    return schema[: -len("Response")] if schema.endswith("Response") else schema


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


_CODE_SPAN = re.compile(r"(`[^`]*`)")
_URL = re.compile(r"(?<![<(])\bhttps?://[^\s)>`]+")


def doc_text(text: str) -> str:
    """Escape Markdown that rustdoc would treat as links or HTML, outside code spans."""
    out = []
    for i, part in enumerate(_CODE_SPAN.split(text)):
        if i % 2 == 1:
            out.append(part)
            continue
        part = re.sub(r"([\[\]<>])", r"\\\1", part)
        part = _URL.sub(lambda m: "<" + m.group(0) + ">", part)
        out.append(part)
    return "".join(out)


def doc(text: str | None, indent: str = "") -> str:
    if not text:
        return ""
    lines = [ln.rstrip() for ln in text.strip().splitlines()]
    return "".join(f"{indent}///{(' ' + doc_text(ln.strip())) if ln.strip() else ''}\n" for ln in lines)


class Gen:
    def __init__(self, spec: dict, surface: dict, error_codes: list[str]):
        self.spec = spec
        self.schemas = spec["components"]["schemas"]
        self.surface = surface
        self.error_codes = error_codes

    # -- types ---------------------------------------------------------------------------

    def base_type(self, s: dict) -> tuple[str, str]:
        """(Rust type, kind) with kind "container" (Vec/map: empty by default), "value" or "json"."""
        if "$ref" in s:
            name = ref_name(s["$ref"])
            if name == "Amount":
                return "Amount", "value"
            if name == "DetailValue":
                return "serde_json::Value", "json"
            return rust_name(name), "value"
        if "allOf" in s and len(s["allOf"]) == 1:
            return self.base_type(s["allOf"][0])
        t = s.get("type")
        if t == "string":
            if s.get("format") == "date-time":
                return "DateTime<Utc>", "value"
            return "String", "value"
        if t == "integer":
            return ("i32" if s.get("format") == "int32" else "i64"), "value"
        if t == "boolean":
            return "bool", "value"
        if t == "array":
            inner, _ = self.base_type(s["items"])
            return f"Vec<{inner}>", "container"
        if t == "object" and "additionalProperties" in s:
            inner, _ = self.base_type(s["additionalProperties"])
            return f"BTreeMap<String, {inner}>", "container"
        if t == "object":
            return "serde_json::Map<String, serde_json::Value>", "container"
        if t is None and not ({"oneOf", "anyOf", "enum"} & set(s)):
            return "serde_json::Value", "json"  # untyped in the spec: kept as raw JSON
        raise SystemExit(f"unsupported schema: {json.dumps(s)[:200]}")

    def field(self, s: dict, required: bool) -> tuple[str, str]:
        """(Rust type, serde attribute or "")."""
        typ, kind = self.base_type(s)
        if kind == "container":
            return typ, "#[serde(default)]"
        if kind == "json":
            return typ, "#[serde(default, skip_serializing_if = \"serde_json::Value::is_null\")]"
        if (not required) or s.get("nullable", False):
            return f"Option<{typ}>", "#[serde(default, skip_serializing_if = \"Option::is_none\")]"
        return typ, ""

    # -- models --------------------------------------------------------------------------

    def models(self) -> str:
        out: list[str] = [HEADER,
                          "//! API models, generated from the shared OpenAPI document.\n\n",
                          "#![allow(clippy::doc_markdown, clippy::too_many_arguments)]\n\n",
                          "use std::collections::BTreeMap;\n\n",
                          "use chrono::{DateTime, Utc};\n",
                          "use serde::{Deserialize, Serialize};\n\n",
                          "use crate::amount::Amount;\n\n"]
        for name in sorted(self.schemas):
            if name in SKIP_SCHEMAS:
                continue
            s = self.schemas[name]
            rname = rust_name(name)
            if "enum" in s:
                extra = CLIENT_ERROR_CODES if name == "ErrorCode" else {}
                out.append(self.enum(rname, s, extra))
            elif s.get("type") == "object" and "properties" in s:
                out.append(self.struct(rname, s, name.endswith("Request")))
            else:
                raise SystemExit(f"schema {name} is neither an enum nor an object")
        body = "".join(out)
        if "BTreeMap<" not in body.split("use crate::amount::Amount;", 1)[1]:
            body = body.replace("use std::collections::BTreeMap;\n\n", "")
        if "DateTime<Utc>" not in body.split("use crate::amount::Amount;", 1)[1]:
            body = body.replace("use chrono::{DateTime, Utc};\n", "")
        return body

    def enum(self, rname: str, s: dict, extra: dict[str, str]) -> str:
        docs = (doc(s.get("description"), "    ") or f"    /// {rname}: an API enum.\n") + \
            "    ///\n    /// The type is open: values added to the API later decode as `Other`.\n"
        lines = ["open_enum! {\n", docs, f"    {rname} {{\n"]
        for v in s["enum"]:
            lines.append(f"        {pascal(str(v))} => {json.dumps(v)},\n")
        for v, text in extra.items():
            lines.append(doc(text, "        "))
            lines.append(f"        {pascal(v)} => {json.dumps(v)},\n")
        lines.append("    }\n}\n\n")
        return "".join(lines)

    def struct(self, rname: str, s: dict, is_request: bool) -> str:
        required = set(s.get("required", []))
        derive = "Debug, Clone, PartialEq, Serialize, Deserialize"
        if is_request and not [p for p in s.get("required", [])]:
            derive += ", Default"
        lines = [doc(s.get("description")) or f"/// {rname}: an API object.\n",
                 f"#[derive({derive})]\n",
                 f"pub struct {rname} {{\n"]
        req_args: list[tuple[str, str]] = []
        others: list[tuple[str, str]] = []
        for prop in sorted(s["properties"]):
            ps = s["properties"][prop]
            typ, attr = self.field(ps, prop in required)
            fname = snake(prop)
            lines.append(doc(ps.get("description"), "    ") or f"    /// `{prop}`\n")
            if fname.removeprefix("r#") != prop:
                lines.append(f"    #[serde(rename = {json.dumps(prop)})]\n")
            if attr:
                lines.append(f"    {attr}\n")
            lines.append(f"    pub {fname}: {typ},\n")
            if typ.startswith("Option<") or attr == "#[serde(default)]":
                others.append((fname, "Default::default()" if not typ.startswith("Option<") else "None"))
            else:
                req_args.append((fname, typ))
        lines.append("}\n\n")
        if is_request and req_args:
            order = [snake(r) for r in s.get("required", [])]
            req_args.sort(key=lambda a: order.index(a[0]) if a[0] in order else len(order))
            args = ", ".join(f"{f}: {self.arg_type(t)}" for f, t in req_args)
            inits = [self.init(f, t) for f, t in req_args] + [f"{f}: {v}" for f, v in others]
            lines.append(f"impl {rname} {{\n")
            what = ", ".join(f.removeprefix('r#') for f, _ in req_args) or "nothing"
            lines.append(f"    /// A request with the required fields ({what}); the optional ones are unset.\n")
            lines.append(f"    pub fn new({args}) -> Self {{\n        Self {{ {', '.join(inits)} }}\n    }}\n}}\n\n")
        return "".join(lines)

    @staticmethod
    def init(f: str, t: str) -> str:
        return f"{f}: {f}.into()" if t == "String" else f

    @staticmethod
    def arg_type(t: str) -> str:
        return "impl Into<String>" if t == "String" else t

    # -- operations ----------------------------------------------------------------------

    def ops(self) -> list[tuple]:
        allowed = {(o["method"].upper(), o["path"]): o for o in self.surface["operations"]}
        ops = []
        for path, item in self.spec["paths"].items():
            for method, op in item.items():
                if method not in ("get", "post", "delete", "put", "patch"):
                    continue
                key = (method.upper(), path)
                if key not in allowed:
                    raise SystemExit(f"{method.upper()} {path} is in the spec but not in surface.yaml")
                ops.append((op["operationId"], method.upper(), path, allowed[key], op))
        missing = set(allowed) - {(m, p) for _, m, p, _, _ in ops}
        if missing:
            raise SystemExit(f"surface.yaml operations missing from the spec: {sorted(missing)}")
        ops.sort(key=lambda o: o[0])
        return ops

    def operations(self) -> str:
        ops = self.ops()
        spec_codes = self.schemas["ErrorCode"]["enum"]
        if spec_codes != self.error_codes:
            raise SystemExit("errors.yaml and the spec's ErrorCode enum disagree; rebuild cexy-api-spec")

        out = [HEADER, "//! The SDK surface (operation table) and query-parameter structs, generated from the\n"
                       "//! shared OpenAPI document.\n\n",
               "#![allow(clippy::doc_markdown)]\n\n",
               "use chrono::{DateTime, SecondsFormat, Utc};\n\n",
               "use crate::models_gen::*;\n\n"]
        out.append("/// The `info.version` of the SDK spec this crate was generated from.\n")
        out.append(f"pub const SPEC_VERSION: &str = {json.dumps(self.spec['info']['version'])};\n\n")

        out.append("/// One operation of the SDK surface.\n"
                   "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n"
                   "#[non_exhaustive]\npub enum OperationId {\n")
        for op_id, *_ in ops:
            out.append(f"    /// `{op_id}`\n    {pascal(op_id)},\n")
        out.append("}\n\n")

        out.append("/// Method, path, authentication and required API-key scope of an operation.\n"
                   "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n"
                   "pub struct OperationInfo {\n"
                   "    /// HTTP method, upper case.\n    pub method: &'static str,\n"
                   "    /// Path template, such as `/api/v1/markets/{symbol}`.\n    pub path: &'static str,\n"
                   "    /// `\"none\"` or `\"api_key\"`.\n    pub auth: &'static str,\n"
                   "    /// `\"\"`, `\"read\"` or `\"trade\"`.\n    pub scope: &'static str,\n"
                   "}\n\n")
        out.append("impl OperationId {\n")
        out.append(f"    /// Every operation of the SDK surface ({len(ops)}).\n")
        out.append(f"    pub const ALL: [OperationId; {len(ops)}] = [\n")
        for op_id, *_ in ops:
            out.append(f"        OperationId::{pascal(op_id)},\n")
        out.append("    ];\n\n")
        out.append("    /// The API's operationId, such as `\"place_order\"`.\n"
                   "    pub fn as_str(self) -> &'static str {\n        match self {\n")
        for op_id, *_ in ops:
            out.append(f"            OperationId::{pascal(op_id)} => {json.dumps(op_id)},\n")
        out.append("        }\n    }\n\n")
        out.append("    /// Method, path, authentication and scope.\n"
                   "    pub fn info(self) -> OperationInfo {\n        match self {\n")
        for op_id, method, path, allow, _ in ops:
            scope = allow.get("scope", "-")
            scope = "" if scope == "-" else scope
            out.append(f"            OperationId::{pascal(op_id)} => OperationInfo {{ method: {json.dumps(method)}, "
                       f"path: {json.dumps(path)}, auth: {json.dumps(allow['auth'])}, scope: {json.dumps(scope)} }},\n")
        out.append("        }\n    }\n}\n\n")

        written: set[str] = set()
        for op_id, _, _, _, op in ops:
            params = [p for p in op.get("parameters", []) if p["in"] == "query"]
            if not params:
                continue
            name = SHARED_PARAMS.get(op_id, pascal(op_id) + "Params")
            if name in written:
                continue
            written.add(name)
            out.append(self.params(name, op_id, params))
        return "".join(out)

    def params(self, name: str, op_id: str, params: list[dict]) -> str:
        users = sorted(k for k, v in SHARED_PARAMS.items() if v == name) or [op_id]
        fields = []  # (field name, wire name, type, required, description)
        for prm in params:
            s = prm["schema"]
            req = prm.get("required", False)
            base, _ = self.base_type(s)
            typ = base if req else f"Option<{base}>"
            desc = prm.get("description") or s.get("description")
            if req:
                desc = ((desc or "").rstrip() + "\n\nRequired.").lstrip()
            fields.append((snake(prm["name"]), prm["name"], typ, base, req, desc))
        defaultable = all((not req) or base in ("String", "i32", "i64", "bool") for _, _, _, base, req, _ in fields)
        derive = "Debug, Clone, PartialEq" + (", Default" if defaultable else "")
        lines = [f"/// Query parameters of {', '.join('`' + u + '`' for u in users)}. `None` is not sent.\n",
                 f"#[derive({derive})]\npub struct {name} {{\n"]
        for fname, wire, typ, _, _, desc in fields:
            lines.append(doc(desc, "    ") or f"    /// `{wire}`\n")
            lines.append(f"    pub {fname}: {typ},\n")
        lines.append("}\n\n")

        req_fields = [f for f in fields if f[4]]
        lines.append(f"impl {name} {{\n")
        if req_fields:
            args = ", ".join(f"{f[0]}: {self.arg_type(f[2])}" for f in req_fields)
            inits = ", ".join(self.init(f[0], f[2]) if f[4] else f"{f[0]}: None" for f in fields)
            lines.append("    /// Parameters with the required values; the optional ones are unset.\n")
            lines.append(f"    pub fn new({args}) -> Self {{\n        Self {{ {inits} }}\n    }}\n\n")
        lines.append("    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {\n"
                     "        let mut q = Vec::new();\n")
        for fname, wire, typ, base, req, _ in fields:
            conv = {
                "String": "v.clone()",
                "i32": "v.to_string()",
                "i64": "v.to_string()",
                "bool": "v.to_string()",
                "DateTime<Utc>": "v.to_rfc3339_opts(SecondsFormat::AutoSi, true)",
            }.get(base, "v.as_str().to_string()")
            if req:
                lines.append(f"        {{\n            let v = &self.{fname};\n"
                             f"            q.push(({json.dumps(wire)}, {conv}));\n        }}\n")
            else:
                lines.append(f"        if let Some(v) = &self.{fname} {{\n"
                             f"            q.push(({json.dumps(wire)}, {conv}));\n        }}\n")
        lines.append("        q\n    }\n}\n\n")
        return "".join(lines)


def rustfmt(src: str) -> str:
    binary = os.environ.get("RUSTFMT", "rustfmt")
    try:
        res = subprocess.run([binary, "--edition", "2024", "--emit", "stdout"], input=src, capture_output=True,
                             text=True)
    except FileNotFoundError:
        raise SystemExit(f"{binary} not found: install rustfmt (rustup component add rustfmt), or set $RUSTFMT")
    if res.returncode != 0:
        raise SystemExit(f"rustfmt failed:\n{res.stderr}")
    return res.stdout


def main() -> int:
    check = "--check" in sys.argv[1:]
    spec = json.loads((SPEC_DIR / "spec" / "openapi.sdk.json").read_text())
    surface = yaml.safe_load((SPEC_DIR / "surface.yaml").read_text())
    codes = yaml.safe_load((SPEC_DIR / "errors.yaml").read_text())["codes"]
    gen = Gen(spec, surface, codes)
    outputs = {MODELS: rustfmt(gen.models()), OPERATIONS: rustfmt(gen.operations())}
    stale = [p.name for p, src in outputs.items() if not p.exists() or p.read_text() != src]
    if check:
        if stale:
            print(f"out of date: {', '.join(stale)}; run python3 tools/generate.py", file=sys.stderr)
            return 1
        print("generated files are up to date")
        return 0
    for p, src in outputs.items():
        p.write_text(src)
    print(f"wrote {', '.join(str(p.relative_to(ROOT)) for p in outputs)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
