// Code generated by tools/generate.py from cexy-api-spec; DO NOT EDIT.

//! API models, generated from the shared OpenAPI document.

#![allow(clippy::doc_markdown, clippy::too_many_arguments)]

use std::collections::BTreeMap;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::amount::Amount;

/// The id of the account a credential belongs to, and nothing else.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AccountId {
    /// Account id: the same hex as the realtime `authenticated` reply's `user_id`.
    pub user_id: String,
}

/// An existing key. Never carries the secret.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ApiKey {
    /// Permitted source addresses. Empty means unrestricted.
    #[serde(default)]
    pub allowed_ips: Vec<String>,
    /// When it was created.
    pub created_at: DateTime<Utc>,
    /// When it stops working.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
    /// Opaque key identifier, used to revoke it.
    pub id: String,
    /// The public key id, sent as `X-API-Key`.
    pub key_id: String,
    /// Human label.
    pub label: String,
    /// When it was last used, if ever.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<DateTime<Utc>>,
    /// Whether it has been revoked.
    pub revoked: bool,
    /// Granted scopes.
    #[serde(default)]
    pub scopes: Vec<ApiScope>,
}

open_enum! {
    /// Scope attached to an API key.
    ///
    /// Scopes narrow what an API key may do. They apply to API keys only: a signed-in session carries none and is not limited by them.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    ApiScope {
        Read => "read",
        Trade => "trade",
    }
}

/// An asset's policy on one network.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AssetNetwork {
    /// Contract address or chain asset id, for a token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contract_address: Option<String>,
    /// Confirmations before a deposit is credited.
    pub deposit_confirmations: i32,
    /// Whether deposits are accepted.
    pub deposit_enabled: bool,
    /// `maintenance`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maintenance: Option<MaintenanceState>,
    /// `max_withdrawal`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_withdrawal: Option<Amount>,
    /// What to call the memo field in a UI.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memo_label: Option<String>,
    /// Whether a memo is mandatory.
    pub memo_required: bool,
    /// Whether the network uses a memo / destination tag.
    pub memo_supported: bool,
    /// `min_deposit`
    pub min_deposit: Amount,
    /// `min_withdrawal`
    pub min_withdrawal: Amount,
    /// Network code.
    pub network: String,
    /// Network display name.
    pub network_name: String,
    /// Operator note.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notice: Option<String>,
    /// How the asset exists on this chain.
    pub token_kind: String,
    /// Decimal places a withdrawal amount is truncated to.
    pub withdrawal_decimals: i32,
    /// Whether withdrawals are accepted.
    pub withdrawal_enabled: bool,
    /// `withdrawal_fee`
    pub withdrawal_fee: Amount,
    /// Asset the withdrawal fee is charged in.
    pub withdrawal_fee_asset: String,
}

/// A tradable asset.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Asset {
    /// Accounting precision: the decimal places the exchange records internally.
    ///
    /// Use this for arithmetic. For rendering, use `display_decimals`.
    pub decimals: i32,
    /// Decimal places to show in a user interface.
    ///
    /// Always less than or equal to `decimals`. Rounding for display is presentation only and must never be fed back into a request.
    pub display_decimals: i32,
    /// Identifier for a client-bundled icon, when no logo URL is set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon_key: Option<String>,
    /// Logo URL, when the operator has configured one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<String>,
    /// How old this asset's price may be before it is refused, in seconds.
    ///
    /// The global default unless an operator set an override for this asset. Exposed beside the flag because the flag alone cannot explain itself: an asset that is not stale after a week and one that is not stale after an hour look identical without it.
    pub max_price_age_secs: i64,
    /// Display name.
    pub name: String,
    /// Networks this asset can be deposited to or withdrawn from.
    #[serde(default)]
    pub networks: Vec<AssetNetwork>,
    /// Operator note, e.g. why deposits are paused.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notice: Option<String>,
    /// Uppercase ticker.
    pub symbol: String,
    /// Whether the asset may appear in markets.
    pub trading_enabled: bool,
    /// `usd_price`
    pub usd_price: Amount,
    /// Whether that price is too old to compute with.
    ///
    /// When true, the exchange refuses to derive anything from it: daily limits and auto-approval fail closed rather than guess, and a stored USD value is recorded as absent rather than as a confident wrong figure.
    pub usd_price_stale: bool,
    /// When that price was last set.
    ///
    /// Exposed because the price is typed in by an operator and refreshed by nothing — there is no feed. Without the timestamp a caller cannot tell a price set an hour ago from one set last month, and both look equally authoritative.
    pub usd_price_updated_at: DateTime<Utc>,
    /// Project website.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub website_url: Option<String>,
}

/// A balance in one asset.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Balance {
    /// Asset symbol.
    pub asset: String,
    /// `available`
    pub available: Amount,
    /// Internal transfers to this account still held, soonest released first; empty when none. Their sum is part of `locked`. Shows at most 100.
    #[serde(default)]
    pub held_incoming: Vec<HeldIncoming>,
    /// `locked`
    pub locked: Amount,
    /// `pending`
    pub pending: Amount,
    /// This balance's sequence: it rises with every change to it, and `balance.updated` carries the same number as `data.sequence`. Apply an event only if its sequence is greater than the one this snapshot holds. 0 for a balance never touched.
    #[serde(default)]
    pub sequence: i64,
    /// `total`
    pub total: Amount,
}

/// Arms, re-arms or disarms the dead-man switch.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CancelAllAfterRequest {
    /// One market's orders only. Omitted or `null`, the switch covers every market. A per-market switch and the all-markets switch are separate: each fires on its own.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Milliseconds from now after which the open orders in scope are cancelled, unless the switch is armed again first: from 5000 to 600000. `0` disarms.
    pub timeout_ms: i64,
}

impl CancelAllAfterRequest {
    /// A request with the required fields (timeout_ms); the optional ones are unset.
    pub fn new(timeout_ms: i64) -> Self {
        Self {
            timeout_ms,
            symbol: None,
        }
    }
}

/// The dead-man switch, as just set.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CancelAllAfter {
    /// Whether a deadline is now armed for this scope. `false` after a disarm.
    pub armed: bool,
    /// When the orders are cancelled unless armed again. `null` when disarmed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<DateTime<Utc>>,
    /// The server's clock when the switch was set, to measure the deadline against.
    pub server_time: DateTime<Utc>,
    /// The market it covers, or `null` for every market.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// The timeout asked for, in milliseconds.
    pub timeout_ms: i64,
}

/// Cancels every open order, optionally within one market.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct CancelAllRequest {
    /// Limit the cancellation to one market. Omitted or `null`, every market's open orders are cancelled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
}

/// What a bulk cancellation achieved.
///
/// Every order the call handled is in exactly one of `cancelled`, `already_closed` and `failed`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CancelAllResult {
    /// Orders that closed on their own (filled, rejected, cancelled elsewhere) before this call reached them. Nothing was done to them, and they are not failures.
    #[serde(default)]
    pub already_closed: Vec<String>,
    /// Orders cancelled.
    #[serde(default)]
    pub cancelled: Vec<String>,
    /// Orders that could not be cancelled in this call. Check `failures` for why, then refresh or call again.
    #[serde(default)]
    pub failed: Vec<String>,
    /// Why each order in `failed` could not be cancelled.
    #[serde(default)]
    pub failures: Vec<CancelFailure>,
    /// More open orders exist than one call handles (500). Call again.
    pub has_more: bool,
}

/// Why one order could not be cancelled.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CancelFailure {
    /// The error code of the attempt, as in any error response: e.g. `INVALID_STATE` for an order still being placed when the wait ran out, or `MARKET_UNAVAILABLE`.
    pub code: String,
    /// Its message.
    pub message: String,
    /// The order.
    pub order_id: String,
}

/// One candle.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesCandle {
    /// `close`
    pub close: Amount,
    /// Close time, unix milliseconds.
    pub close_time: i64,
    /// `high`
    pub high: Amount,
    /// `low`
    pub low: Amount,
    /// `open`
    pub open: Amount,
    /// Open time, unix milliseconds.
    pub open_time: i64,
    /// Number of trades.
    pub trades: i64,
    /// `volume`
    pub volume: Amount,
}

open_enum! {
    /// Candle/kline intervals for market data.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    CandleInterval {
        M1 => "1m",
        M5 => "5m",
        M15 => "15m",
        M30 => "30m",
        H1 => "1h",
        H4 => "4h",
        D1 => "1d",
        W1 => "1w",
    }
}

/// An OHLCV bucket.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Candle {
    /// `close`
    pub close: Amount,
    /// `high`
    pub high: Amount,
    /// `low`
    pub low: Amount,
    /// `open`
    pub open: Amount,
    /// Bucket start.
    pub open_time: DateTime<Utc>,
    /// `quote_volume`
    pub quote_volume: Amount,
    /// Number of trades.
    pub trade_count: i64,
    /// `volume`
    pub volume: Amount,
}

/// A deposit address.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DepositAddress {
    /// The address to send to.
    pub address: String,
    /// Asset symbol.
    pub asset: String,
    /// When the address was issued.
    pub created_at: DateTime<Utc>,
    /// Confirmations before the deposit is credited.
    pub deposit_confirmations: i32,
    /// Memo / destination tag. **Required when present** — a deposit without it may be unrecoverable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    /// What to call the memo field in a UI.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memo_label: Option<String>,
    /// `min_deposit`
    pub min_deposit: Amount,
    /// Network code.
    pub network: String,
}

/// Unique identifier of a deposit.
pub type DepositId = String;

/// A deposit.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Deposit {
    /// Address that received it.
    pub address: String,
    /// `amount`
    pub amount: Amount,
    /// Asset symbol.
    pub asset: String,
    /// Confirmations observed.
    pub confirmations: i32,
    /// When it was credited.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub credited_at: Option<DateTime<Utc>>,
    /// Explorer link, when the network has one configured.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub explorer_url: Option<String>,
    /// When it was first observed.
    pub first_seen_at: DateTime<Utc>,
    /// Deposit id.
    pub id: String,
    /// Memo, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    /// Network code.
    pub network: String,
    /// Operator note, e.g. why it was reversed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// Position within the transaction. Distinguishes two outputs of one transaction.
    pub output_index: i32,
    /// Confirmations required to credit.
    pub required_confirmations: i32,
    /// `status`
    pub status: DepositStatus,
    /// Transaction hash.
    pub txid: String,
}

open_enum! {
    /// Lifecycle of an incoming blockchain deposit.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    DepositStatus {
        Detected => "detected",
        Credited => "credited",
        Reversed => "reversed",
        Orphaned => "orphaned",
        BelowMinimum => "below_minimum",
        UnderReview => "under_review",
        Internal => "internal",
    }
}

open_enum! {
    /// Stable, machine-readable error identifiers.
    ///
    /// Serialized as `SCREAMING_SNAKE_CASE`. Adding a variant is backwards-compatible; renaming or removing one is a breaking API change.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    ErrorCode {
        ValidationFailed => "VALIDATION_FAILED",
        MalformedRequest => "MALFORMED_REQUEST",
        InvalidCursor => "INVALID_CURSOR",
        PrecisionExceeded => "PRECISION_EXCEEDED",
        BelowMinimum => "BELOW_MINIMUM",
        AboveMaximum => "ABOVE_MAXIMUM",
        InvalidAddress => "INVALID_ADDRESS",
        MemoRequired => "MEMO_REQUIRED",
        Unauthenticated => "UNAUTHENTICATED",
        InvalidCredentials => "INVALID_CREDENTIALS",
        TokenExpired => "TOKEN_EXPIRED",
        SessionRevoked => "SESSION_REVOKED",
        TwoFactorRequired => "TWO_FACTOR_REQUIRED",
        TwoFactorInvalid => "TWO_FACTOR_INVALID",
        FreshTwoFactorRequired => "FRESH_TWO_FACTOR_REQUIRED",
        Forbidden => "FORBIDDEN",
        ApiKeyNotAllowed => "API_KEY_NOT_ALLOWED",
        KeyNotSignable => "KEY_NOT_SIGNABLE",
        SignatureExpired => "SIGNATURE_EXPIRED",
        NonceReused => "NONCE_REUSED",
        SignatureRequired => "SIGNATURE_REQUIRED",
        FuturesRestricted => "FUTURES_RESTRICTED",
        AccountFrozen => "ACCOUNT_FROZEN",
        AccountOnHold => "ACCOUNT_ON_HOLD",
        EmailNotVerified => "EMAIL_NOT_VERIFIED",
        RegionBlocked => "REGION_BLOCKED",
        JurisdictionBlocked => "JURISDICTION_BLOCKED",
        NotFound => "NOT_FOUND",
        MethodNotAllowed => "METHOD_NOT_ALLOWED",
        AlreadyExists => "ALREADY_EXISTS",
        InvalidState => "INVALID_STATE",
        IdempotencyKeyConflict => "IDEMPOTENCY_KEY_CONFLICT",
        WindowOpen => "WINDOW_OPEN",
        EvidenceContradicts => "EVIDENCE_CONTRADICTS",
        AmountMismatch => "AMOUNT_MISMATCH",
        ConcurrentModification => "CONCURRENT_MODIFICATION",
        DeadManNotArmed => "DEAD_MAN_NOT_ARMED",
        InsufficientFunds => "INSUFFICIENT_FUNDS",
        InsufficientFeeFunds => "INSUFFICIENT_FEE_FUNDS",
        MarketUnavailable => "MARKET_UNAVAILABLE",
        DepositDisabled => "DEPOSIT_DISABLED",
        WithdrawalDisabled => "WITHDRAWAL_DISABLED",
        SelfTradeBlocked => "SELF_TRADE_BLOCKED",
        LimitExceeded => "LIMIT_EXCEEDED",
        PriceUnavailable => "PRICE_UNAVAILABLE",
        RateLimited => "RATE_LIMITED",
        Internal => "INTERNAL",
        ServiceUnavailable => "SERVICE_UNAVAILABLE",
        UnderMaintenance => "UNDER_MAINTENANCE",
        EngineOverloaded => "ENGINE_OVERLOADED",
        /// The server answered with a redirect (3xx). The SDK never follows redirects, so
        /// credentials and orders are never re-sent to another URL. Set by the SDK; the API
        /// never sends it.
        UnexpectedRedirect => "UNEXPECTED_REDIRECT",
    }
}

/// Public exchange configuration.
///
/// Everything a frontend needs to render itself without a deploy: branding, limits, supported intervals, and whether the exchange is in maintenance.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ExchangeConfig {
    /// Candle intervals the API serves.
    #[serde(default)]
    pub candle_intervals: Vec<CandleInterval>,
    /// Default page size for paginated endpoints.
    pub default_page_size: i32,
    /// Whether registration verifies the email address with an emailed code before the authenticator step. Lets a signup form show the right number of steps up front.
    pub email_verification_required: bool,
    /// Feature flags a frontend may use to hide unavailable functionality.
    ///
    /// Presentation only. The backend enforces every rule independently.
    #[serde(default)]
    pub features: BTreeMap<String, bool>,
    /// Message to show while in maintenance.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maintenance_message: Option<String>,
    /// Whether the exchange is in maintenance mode.
    pub maintenance_mode: bool,
    /// Maximum page size.
    pub max_page_size: i32,
    /// Display name.
    pub name: String,
    /// `password_rules`
    pub password_rules: PasswordRules,
    /// Whether new registrations are accepted.
    pub registration_enabled: bool,
    /// Support contact.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub support_url: Option<String>,
    /// Seconds a verified two-factor code authorises sensitive actions for.
    pub two_factor_freshness_seconds: i64,
    /// Where to open the realtime connection, relative to this API's origin.
    pub websocket_path: String,
    /// The realtime protocol version this server speaks.
    pub websocket_protocol_version: i32,
}

/// Removes liquidity from a pool.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ExitPoolRequest {
    /// `shares`
    pub shares: Amount,
}

impl ExitPoolRequest {
    /// A request with the required fields (shares); the optional ones are unset.
    pub fn new(shares: Amount) -> Self {
        Self { shares }
    }
}

/// What an exit produced.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ExitPoolResult {
    /// `base_returned`
    pub base_returned: Amount,
    /// `quote_returned`
    pub quote_returned: Amount,
    /// `shares_burned`
    pub shares_burned: Amount,
    /// `shares_held`
    pub shares_held: Amount,
}

/// A fee tier.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FeeSchedule {
    /// Human label.
    pub label: String,
    /// Maker rate, as a percentage.
    pub maker_fee_percent: String,
    /// `min_30d_volume_usd`
    pub min_30d_volume_usd: Amount,
    /// Taker rate, as a percentage.
    pub taker_fee_percent: String,
    /// Tier index.
    pub tier: i32,
}

/// One fill.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesFill {
    /// `closed_pnl`
    pub closed_pnl: Amount,
    /// Coin.
    pub coin: String,
    /// The provider's description of the fill's effect (`Open Long`, `Close Short`, ...).
    pub direction: String,
    /// Our id for it.
    pub id: String,
    /// Our id for its order.
    pub order_id: String,
    /// `price`
    pub price: Amount,
    /// `buy` or `sell`.
    pub side: String,
    /// `size`
    pub size: Amount,
    /// Whether this fill took liquidity.
    pub taker: bool,
    /// When, unix milliseconds.
    pub time: i64,
}

/// One of the caller's executions.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Fill {
    /// `fee`
    pub fee: Amount,
    /// Asset the fee was charged in.
    pub fee_asset: String,
    /// The caller's order.
    pub order_id: String,
    /// `price`
    pub price: Amount,
    /// `quantity`
    pub quantity: Amount,
    /// `quote_quantity`
    pub quote_quantity: Amount,
    /// `role`
    pub role: LiquidityRole,
    /// `side`
    pub side: OrderSide,
    /// Market symbol.
    pub symbol: String,
    /// When it executed.
    pub timestamp: DateTime<Utc>,
    /// Trade id.
    pub trade_id: String,
}

/// One funding payment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Funding {
    /// `amount`
    pub amount: Amount,
    /// Coin.
    pub coin: String,
    /// `position_size`
    pub position_size: Amount,
    /// `rate`
    pub rate: Amount,
    /// When, unix milliseconds.
    pub time: i64,
}

/// A futures market's book.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesBook {
    /// When the provider last sent it.
    pub as_of: DateTime<Utc>,
    /// Asks, best first.
    #[serde(default)]
    pub asks: Vec<Level>,
    /// Bids, best first.
    #[serde(default)]
    pub bids: Vec<Level>,
    /// Coin.
    pub coin: String,
    /// The live feed is not healthy: the book may be out of date.
    pub stale: bool,
}

/// A futures market's candles.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesCandles {
    /// When read.
    pub as_of: DateTime<Utc>,
    /// Candles, oldest first.
    #[serde(default)]
    pub candles: Vec<FuturesCandle>,
    /// Coin.
    pub coin: String,
    /// Interval.
    pub interval: String,
    /// Older than it should be.
    pub stale: bool,
}

/// A page of the account's fills.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesFills {
    /// Newest first; fills sharing a millisecond in a fixed order. A page may be short of 100 and still be followed by more.
    #[serde(default)]
    pub fills: Vec<FuturesFill>,
    /// Whether the account has a futures account.
    pub has_account: bool,
    /// Pass as `cursor` for older fills, exactly as given; `null` at the end (30 days back). Opaque: it may carry more than a time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

/// A page of the account's funding payments.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesFunding {
    /// Newest first.
    #[serde(default)]
    pub funding: Vec<Funding>,
    /// Whether the account has a futures account.
    pub has_account: bool,
    /// Pass as `cursor` for older payments, exactly as given; `null` at the end (30 days back). Opaque.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

/// One futures market.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesMarket {
    /// When this data was read.
    pub as_of: DateTime<Utc>,
    /// `market`
    pub market: PerpMarket,
    /// Older than it should be.
    pub stale: bool,
}

/// Every listed futures market.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesMarkets {
    /// When this data was read from the futures provider.
    pub as_of: DateTime<Utc>,
    /// The markets, in the provider's order. Delisted markets are not included.
    #[serde(default)]
    pub markets: Vec<PerpMarket>,
    /// The data is older than it should be: the provider could not be read just now.
    pub stale: bool,
}

/// The account's open orders.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesOpenOrders {
    /// When read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub as_of: Option<DateTime<Utc>>,
    /// Whether the account has a futures account.
    pub has_account: bool,
    /// The open orders.
    #[serde(default)]
    pub orders: Vec<OpenOrder>,
    /// Older than it should be.
    pub stale: bool,
}

/// The account's positions.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesPositions {
    /// When read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub as_of: Option<DateTime<Utc>>,
    /// Whether the account has a futures account. Without one, nothing else is meaningful.
    pub has_account: bool,
    /// `positions`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub positions: Option<Positions>,
    /// Older than it should be.
    pub stale: bool,
}

/// A futures market's recent public trades.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesTrades {
    /// Coin.
    pub coin: String,
    /// The live feed is not healthy, or was only just opened: trades may be missing.
    pub stale: bool,
    /// Newest first.
    #[serde(default)]
    pub trades: Vec<FuturesPublicTrade>,
}

/// Unique identifier of a futures collateral transfer.
pub type FuturesTransferId = String;

/// An internal transfer credited to `locked` and not yet available.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HeldIncoming {
    /// `amount`
    pub amount: Amount,
    /// When it becomes available, unless an operator cancels it before then.
    pub available_at: DateTime<Utc>,
    /// The transfer.
    pub transfer_id: String,
}

/// Adds liquidity to a pool.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct JoinPoolRequest {
    /// `base_amount`
    pub base_amount: Amount,
    /// `max_ratio_deviation_percent`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_ratio_deviation_percent: Option<Amount>,
    /// `quote_amount`
    pub quote_amount: Amount,
}

impl JoinPoolRequest {
    /// A request with the required fields (base_amount, quote_amount); the optional ones are unset.
    pub fn new(base_amount: Amount, quote_amount: Amount) -> Self {
        Self {
            base_amount,
            quote_amount,
            max_ratio_deviation_percent: None,
        }
    }
}

/// What a join produced.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct JoinPoolResult {
    /// `base_deposited`
    pub base_deposited: Amount,
    /// `quote_deposited`
    pub quote_deposited: Amount,
    /// `shares_held`
    pub shares_held: Amount,
    /// `shares_minted`
    pub shares_minted: Amount,
}

open_enum! {
    /// What a ledger entry records.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    LedgerEntryKind {
        Deposit => "deposit",
        DepositReversal => "deposit_reversal",
        WithdrawalDebit => "withdrawal_debit",
        WithdrawalFee => "withdrawal_fee",
        WithdrawalFeeReserve => "withdrawal_fee_reserve",
        WithdrawalRelease => "withdrawal_release",
        WithdrawalFeeRelease => "withdrawal_fee_release",
        OrderReserve => "order_reserve",
        WithdrawalReserve => "withdrawal_reserve",
        OrderRelease => "order_release",
        TradeDebit => "trade_debit",
        TradeCredit => "trade_credit",
        TradeFee => "trade_fee",
        TransferOut => "transfer_out",
        TransferIn => "transfer_in",
        TransferInHeld => "transfer_in_held",
        TransferRelease => "transfer_release",
        TransferReversal => "transfer_reversal",
        AdjustmentCredit => "adjustment_credit",
        AdjustmentDebit => "adjustment_debit",
        Rebate => "rebate",
        PoolJoin => "pool_join",
        PoolExit => "pool_exit",
        FuturesTransferReserve => "futures_transfer_reserve",
        FuturesTransferRelease => "futures_transfer_release",
        FuturesCollateralSent => "futures_collateral_sent",
        FuturesCollateralReturned => "futures_collateral_returned",
        WithdrawalRefund => "withdrawal_refund",
    }
}

/// One entry from the account's ledger.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LedgerEntry {
    /// Asset symbol.
    pub asset: String,
    /// `available_after`
    pub available_after: Amount,
    /// `available_delta`
    pub available_delta: Amount,
    /// When it was applied.
    pub created_at: DateTime<Utc>,
    /// Entry id.
    pub id: String,
    /// `kind`
    pub kind: LedgerEntryKind,
    /// `locked_delta`
    pub locked_delta: Amount,
    /// `pending_delta`
    pub pending_delta: Amount,
    /// `reference`
    #[serde(default)]
    pub reference: LedgerReference,
    /// Position in this account's history for this asset.
    pub sequence: i64,
}

/// A blockchain deposit.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LedgerReferenceDeposit {
    /// `deposit_id`
    pub deposit_id: DepositId,
}

/// A withdrawal request.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LedgerReferenceWithdrawal {
    /// `withdrawal_id`
    pub withdrawal_id: WithdrawalId,
}

/// An order reservation or release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LedgerReferenceOrder {
    /// `order_id`
    pub order_id: OrderId,
}

/// A trade settlement.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LedgerReferenceTrade {
    /// `order_id`
    pub order_id: OrderId,
    /// `trade_id`
    pub trade_id: TradeId,
}

/// An internal transfer between accounts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LedgerReferenceTransfer {
    /// `counterparty_user_id`
    pub counterparty_user_id: UserId,
    /// Shared reference linking both halves.
    pub transfer_ref: String,
}

/// A manual operator adjustment. Always accompanied by an audit event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LedgerReferenceAdjustment {
    /// `operator_user_id`
    pub operator_user_id: UserId,
}

/// A liquidity pool join or exit.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LedgerReferencePool {
    /// `pool_id`
    pub pool_id: PoolId,
}

/// A movement of collateral to or from a futures account.
///
/// Every entry a transfer produces carries the same one, so the reservation, the release and the completion can be read back as one event — which is what an operator resolving an ambiguous transfer needs.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LedgerReferenceFuturesTransfer {
    /// `futures_transfer_id`
    pub futures_transfer_id: FuturesTransferId,
}

/// A system-originated credit with no user counterparty (rebate, promotion).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LedgerReferenceSystem {
    /// Short machine-readable cause.
    pub cause: String,
}

/// What caused a ledger entry: one kind of cause per variant, told apart by `type`.
///
/// Decoding never fails on a kind this SDK does not know yet (or a known kind with an
/// unexpected shape): it becomes [`LedgerReference::Unknown`] with the raw JSON.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub enum LedgerReference {
    /// `type: "deposit"`
    Deposit(LedgerReferenceDeposit),
    /// `type: "withdrawal"`
    Withdrawal(LedgerReferenceWithdrawal),
    /// `type: "order"`
    Order(LedgerReferenceOrder),
    /// `type: "trade"`
    Trade(LedgerReferenceTrade),
    /// `type: "transfer"`
    Transfer(LedgerReferenceTransfer),
    /// `type: "adjustment"`
    Adjustment(LedgerReferenceAdjustment),
    /// `type: "pool"`
    Pool(LedgerReferencePool),
    /// `type: "futures_transfer"`
    FuturesTransfer(LedgerReferenceFuturesTransfer),
    /// `type: "system"`
    System(LedgerReferenceSystem),
    /// A kind this SDK does not know yet, kept as the raw JSON object.
    Unknown(serde_json::Value),
}

impl Default for LedgerReference {
    /// `Unknown(null)`: what a missing value decodes as.
    fn default() -> Self {
        Self::Unknown(serde_json::Value::Null)
    }
}

impl LedgerReference {
    /// The `type` tag of this value.
    pub fn kind(&self) -> &str {
        match self {
            Self::Deposit(_) => "deposit",
            Self::Withdrawal(_) => "withdrawal",
            Self::Order(_) => "order",
            Self::Trade(_) => "trade",
            Self::Transfer(_) => "transfer",
            Self::Adjustment(_) => "adjustment",
            Self::Pool(_) => "pool",
            Self::FuturesTransfer(_) => "futures_transfer",
            Self::System(_) => "system",
            Self::Unknown(v) => v.get("type").and_then(|t| t.as_str()).unwrap_or(""),
        }
    }
}

impl<'de> Deserialize<'de> for LedgerReference {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let v = serde_json::Value::deserialize(d)?;
        let parsed = match v.get("type").and_then(|t| t.as_str()) {
            Some("deposit") => serde_json::from_value(v.clone()).ok().map(Self::Deposit),
            Some("withdrawal") => serde_json::from_value(v.clone()).ok().map(Self::Withdrawal),
            Some("order") => serde_json::from_value(v.clone()).ok().map(Self::Order),
            Some("trade") => serde_json::from_value(v.clone()).ok().map(Self::Trade),
            Some("transfer") => serde_json::from_value(v.clone()).ok().map(Self::Transfer),
            Some("adjustment") => serde_json::from_value(v.clone()).ok().map(Self::Adjustment),
            Some("pool") => serde_json::from_value(v.clone()).ok().map(Self::Pool),
            Some("futures_transfer") => serde_json::from_value(v.clone())
                .ok()
                .map(Self::FuturesTransfer),
            Some("system") => serde_json::from_value(v.clone()).ok().map(Self::System),
            _ => None,
        };
        Ok(parsed.unwrap_or(Self::Unknown(v)))
    }
}

impl Serialize for LedgerReference {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        let (tag, mut v) = match self {
            Self::Deposit(x) => (
                "deposit",
                serde_json::to_value(x).map_err(serde::ser::Error::custom)?,
            ),
            Self::Withdrawal(x) => (
                "withdrawal",
                serde_json::to_value(x).map_err(serde::ser::Error::custom)?,
            ),
            Self::Order(x) => (
                "order",
                serde_json::to_value(x).map_err(serde::ser::Error::custom)?,
            ),
            Self::Trade(x) => (
                "trade",
                serde_json::to_value(x).map_err(serde::ser::Error::custom)?,
            ),
            Self::Transfer(x) => (
                "transfer",
                serde_json::to_value(x).map_err(serde::ser::Error::custom)?,
            ),
            Self::Adjustment(x) => (
                "adjustment",
                serde_json::to_value(x).map_err(serde::ser::Error::custom)?,
            ),
            Self::Pool(x) => (
                "pool",
                serde_json::to_value(x).map_err(serde::ser::Error::custom)?,
            ),
            Self::FuturesTransfer(x) => (
                "futures_transfer",
                serde_json::to_value(x).map_err(serde::ser::Error::custom)?,
            ),
            Self::System(x) => (
                "system",
                serde_json::to_value(x).map_err(serde::ser::Error::custom)?,
            ),
            Self::Unknown(v) => return v.serialize(s),
        };
        if let serde_json::Value::Object(m) = &mut v {
            m.insert("type".to_owned(), serde_json::Value::String(tag.to_owned()));
        }
        v.serialize(s)
    }
}

/// One price level.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Level {
    /// `price`
    pub price: Amount,
    /// `size`
    pub size: Amount,
}

open_enum! {
    /// Whether a fill added liquidity (maker) or removed it (taker).
    ///
    /// The type is open: values added to the API later decode as `Other`.
    LiquidityRole {
        Maker => "maker",
        Taker => "taker",
    }
}

open_enum! {
    /// Machine-readable reasons a capability is unavailable.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    MaintenanceReason {
        ExchangeMaintenance => "exchange_maintenance",
        NetworkUnavailable => "network_unavailable",
        DepositsDisabled => "deposits_disabled",
        WithdrawalsDisabled => "withdrawals_disabled",
        AssetUnavailable => "asset_unavailable",
    }
}

/// Why a capability is currently unavailable.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MaintenanceState {
    /// Operator-supplied explanation, when there is one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// `reason`
    pub reason: MaintenanceReason,
}

/// A tradable market and its current ticker.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Market {
    /// Base asset symbol.
    pub base_asset: String,
    /// `best_ask`
    pub best_ask: Amount,
    /// `best_bid`
    pub best_bid: Amount,
    /// `change_24h_percent`
    pub change_24h_percent: Amount,
    /// `high_24h`
    pub high_24h: Amount,
    /// `last_price`
    pub last_price: Amount,
    /// Time of the most recent trade.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_trade_at: Option<DateTime<Utc>>,
    /// `lot_size`
    pub lot_size: Amount,
    /// `low_24h`
    pub low_24h: Amount,
    /// `max_quantity`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_quantity: Option<Amount>,
    /// `min_notional`
    pub min_notional: Amount,
    /// `min_quantity`
    pub min_quantity: Amount,
    /// Decimal places a price may carry.
    pub price_decimals: i32,
    /// Decimal places a quantity may carry.
    pub quantity_decimals: i32,
    /// Quote asset symbol.
    pub quote_asset: String,
    /// `quote_volume_24h`
    pub quote_volume_24h: Amount,
    /// `status`
    pub status: MarketStatus,
    /// Order types this market accepts.
    #[serde(default)]
    pub supported_order_types: Vec<OrderType>,
    /// Time-in-force options this market accepts.
    #[serde(default)]
    pub supported_time_in_force: Vec<TimeInForce>,
    /// `BASE/QUOTE`.
    pub symbol: String,
    /// `tick_size`
    pub tick_size: Amount,
    /// When trading opens, for a market not yet live.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trading_starts_at: Option<DateTime<Utc>>,
    /// `volume_24h`
    pub volume_24h: Amount,
}

open_enum! {
    /// Trading availability of a market.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    MarketStatus {
        Active => "active",
        Paused => "paused",
        SellOnly => "sell_only",
        PreTrading => "pre_trading",
        Delisted => "delisted",
    }
}

/// A blockchain network.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Network {
    /// Typical seconds between blocks, for estimating confirmation time.
    pub average_block_seconds: i32,
    /// Stable code.
    pub code: String,
    /// Whether deposits on this network are actually being detected.
    ///
    /// False means either half of the pipeline is down: the last scan pass failed — a refused block range, a rate limit, a node that answers but will not serve logs — or finality could not be established, so deposits are being held rather than credited.
    ///
    /// Deposits sent now will be credited late, whenever the chain recovers, rather than lost. This is the field a status page should use to say deposits are degraded; `reachable` only says the node replies, which it may well do while yielding nothing.
    pub deposits_operational: bool,
    /// Template for an address explorer link. `{address}` is substituted.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub explorer_address_url_template: Option<String>,
    /// Template for a transaction explorer link. `{txid}` is substituted.
    ///
    /// Absent when the operator has configured none; render no link rather than guessing a URL.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub explorer_tx_url_template: Option<String>,
    /// Whether the network is operational.
    pub is_active: bool,
    /// Display name.
    pub name: String,
    /// Whether the node answers at all.
    ///
    /// Narrower than it sounds, and deliberately so: a reachable node can still be failing to yield deposits. Do not render this alone as "network up".
    pub reachable: bool,
}

open_enum! {
    /// What a notice is about.
    ///
    /// A closed enum so a client can render each kind deliberately — an icon, a colour, a link — rather than pattern-matching on prose that may be reworded.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    NotificationKind {
        DepositDetected => "deposit_detected",
        DepositCredited => "deposit_credited",
        WithdrawalRequested => "withdrawal_requested",
        WithdrawalSent => "withdrawal_sent",
        WithdrawalCompleted => "withdrawal_completed",
        WithdrawalFailed => "withdrawal_failed",
        OrderFilled => "order_filled",
        OrderClosed => "order_closed",
        Security => "security",
        ListingDecision => "listing_decision",
        Announcement => "announcement",
    }
}

/// An in-app notice.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Notification {
    /// One or two sentences.
    pub body: String,
    /// When it was created.
    pub created_at: DateTime<Utc>,
    /// Notice id.
    pub id: String,
    /// `kind`
    pub kind: NotificationKind,
    /// Whether it has been read.
    pub read: bool,
    /// The referenced resource's opaque id, for linking.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource_id: Option<String>,
    /// What it refers to: `deposit`, `withdrawal`, `order`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource_type: Option<String>,
    /// Short heading.
    pub title: String,
}

/// One open order.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OpenOrder {
    /// Coin.
    pub coin: String,
    /// Our id for it, stable across reads.
    pub id: String,
    /// The order type as the provider names it (`Limit`, `Stop Market`, ...).
    pub order_type: String,
    /// `original_size`
    pub original_size: Amount,
    /// When placed, unix milliseconds.
    pub placed_at: i64,
    /// `price`
    pub price: Amount,
    /// Whether it may only reduce a position.
    pub reduce_only: bool,
    /// `buy` or `sell`.
    pub side: String,
    /// `size`
    pub size: Amount,
    /// `trigger_price`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger_price: Option<Amount>,
}

/// One side of the order book, aggregated by price.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OrderBook {
    /// Asks, best first.
    #[serde(default)]
    pub asks: Vec<Vec<Amount>>,
    /// Bids, best first, as `[price, quantity]` pairs.
    #[serde(default)]
    pub bids: Vec<Vec<Amount>>,
    /// The realtime sequence this snapshot is current as of.
    ///
    /// Each `orderbook.update` on the `orderbook:{symbol}` websocket channel carries both sides of the top 50 levels in full (`data.full` is always `true`) and replaces the previous state; there are no deltas to buffer. Ignore an update whose `sequence` is at or below the one you hold. A gap only means a book was missed: the next update replaces it whole.
    pub sequence: i64,
    /// Market symbol.
    pub symbol: String,
    /// When this snapshot was taken.
    pub timestamp: DateTime<Utc>,
}

/// Unique identifier of an order.
pub type OrderId = String;

/// An order.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Order {
    /// `average_price`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub average_price: Option<Amount>,
    /// Your identifier, if you supplied one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    /// When it reached a terminal state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<DateTime<Utc>>,
    /// When it was placed.
    pub created_at: DateTime<Utc>,
    /// Asset the fees were charged in.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fee_asset: Option<String>,
    /// `fee_paid`
    pub fee_paid: Amount,
    /// `filled_quantity`
    pub filled_quantity: Amount,
    /// `filled_quote_quantity`
    pub filled_quote_quantity: Amount,
    /// Order id.
    pub id: String,
    /// `price`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub price: Option<Amount>,
    /// `quantity`
    pub quantity: Amount,
    /// `quote_quantity`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quote_quantity: Option<Amount>,
    /// `remaining_quantity`
    pub remaining_quantity: Amount,
    /// `reserved_remaining`
    pub reserved_remaining: Amount,
    /// `side`
    pub side: OrderSide,
    /// `status`
    pub status: OrderStatus,
    /// Why the order was rejected or cancelled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_reason: Option<String>,
    /// `stop_price`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_price: Option<Amount>,
    /// Market symbol.
    pub symbol: String,
    /// `time_in_force`
    pub time_in_force: TimeInForce,
    /// `trigger_direction`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger_direction: Option<TriggerDirection>,
    /// When the trigger fired, if it has.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub triggered_at: Option<DateTime<Utc>>,
    /// `type`
    pub r#type: OrderType,
    /// When it last changed.
    pub updated_at: DateTime<Utc>,
}

open_enum! {
    /// Which side of a market an order takes.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    OrderSide {
        Buy => "buy",
        Sell => "sell",
    }
}

open_enum! {
    /// Lifecycle of an order.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    OrderStatus {
        Pending => "pending",
        Open => "open",
        PartiallyFilled => "partially_filled",
        Filled => "filled",
        Cancelled => "cancelled",
        Rejected => "rejected",
        PendingTrigger => "pending_trigger",
        Expired => "expired",
    }
}

open_enum! {
    /// Order types the matching engine accepts.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    OrderType {
        Limit => "limit",
        Market => "market",
        StopLimit => "stop_limit",
        StopMarket => "stop_market",
    }
}

/// Password constraints, published so a form can validate locally.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PasswordRules {
    /// Whether the password may contain the account's email address.
    pub allows_email_substring: bool,
    /// A short description of any further rules, for display beside the input.
    pub description: String,
    /// Maximum length in characters.
    pub max_length: i64,
    /// Minimum length in characters.
    pub min_length: i64,
}

/// One listed perpetual market and its current figures.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PerpMarket {
    /// The provider's coin name, e.g. `BTC` or `kPEPE`.
    pub coin: String,
    /// `funding_rate`
    pub funding_rate: Amount,
    /// `mark_price`
    pub mark_price: Amount,
    /// The highest leverage allowed.
    pub max_leverage: i32,
    /// `mid_price`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mid_price: Option<Amount>,
    /// `open_interest`
    pub open_interest: Amount,
    /// `oracle_price`
    pub oracle_price: Amount,
    /// `price_24h_ago`
    pub price_24h_ago: Amount,
    /// Decimal places a size may have.
    pub size_decimals: i32,
    /// `volume_24h`
    pub volume_24h: Amount,
}

/// Places an order.
///
/// Set `client_order_id` to make a retry safe: it is unique per account, so a repeat is refused before any funds move, and `GET /trading/orders/by-client-id/{client_order_id}` recovers the outcome. `Idempotency-Key` is not honoured for orders.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlaceOrderRequest {
    /// Your own identifier. Unique per account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    /// `price`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub price: Option<Amount>,
    /// `quantity`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Amount>,
    /// `quote_quantity`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quote_quantity: Option<Amount>,
    /// `side`
    pub side: OrderSide,
    /// `stop_price`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_price: Option<Amount>,
    /// Market symbol.
    pub symbol: String,
    /// `time_in_force`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_in_force: Option<TimeInForce>,
    /// `trigger_direction`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger_direction: Option<TriggerDirection>,
    /// `type`
    pub r#type: OrderType,
}

impl PlaceOrderRequest {
    /// A request with the required fields (symbol, side, type); the optional ones are unset.
    pub fn new(symbol: impl Into<String>, side: OrderSide, r#type: OrderType) -> Self {
        Self {
            symbol: symbol.into(),
            side,
            r#type,
            client_order_id: None,
            price: None,
            quantity: None,
            quote_quantity: None,
            stop_price: None,
            time_in_force: None,
            trigger_direction: None,
        }
    }
}

/// The result of placing an order, including anything it executed immediately.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlaceOrderResponse {
    /// Fills produced on entry, oldest first.
    #[serde(default)]
    pub fills: Vec<Fill>,
    /// `order`
    pub order: Order,
}

/// Unique identifier of a liquidity pool.
pub type PoolId = String;

/// A pool as a client sees it.
///
/// Reserves are the custody account's balances, so they include liquidity currently locked in resting orders. `price` is the curve's mid, which sits between the pool's own best bid and ask by exactly its fee — it is not a traded price.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Pool {
    /// `base_reserve`
    pub base_reserve: Amount,
    /// When the pool was created.
    pub created_at: DateTime<Utc>,
    /// The pool's fee, in percent, priced into every quote it rests.
    pub fee_percent: String,
    /// Identifier.
    pub id: String,
    /// Ladder steps per side.
    pub ladder_steps: i32,
    /// `price`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub price: Option<Amount>,
    /// `quote_reserve`
    pub quote_reserve: Amount,
    /// `shares_outstanding`
    pub shares_outstanding: Amount,
    /// `status`
    pub status: PoolStatus,
    /// Market the pool quotes.
    pub symbol: String,
}

open_enum! {
    /// Whether a pool quotes, and whether it accepts new liquidity.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    PoolStatus {
        Active => "active",
        Paused => "paused",
        Closing => "closing",
    }
}

/// One open position.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Position {
    /// Coin.
    pub coin: String,
    /// `entry_price`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub entry_price: Option<Amount>,
    /// `funding_since_open`
    pub funding_since_open: Amount,
    /// Leverage.
    pub leverage: i32,
    /// `cross` or `isolated`.
    pub leverage_type: String,
    /// `liquidation_price`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub liquidation_price: Option<Amount>,
    /// `margin_used`
    pub margin_used: Amount,
    /// `position_value`
    pub position_value: Amount,
    /// `return_on_equity`
    pub return_on_equity: Amount,
    /// `size`
    pub size: Amount,
    /// `unrealized_pnl`
    pub unrealized_pnl: Amount,
}

/// A margin summary and the open positions.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Positions {
    /// `account_value`
    pub account_value: Amount,
    /// `maintenance_margin`
    pub maintenance_margin: Amount,
    /// `margin_used`
    pub margin_used: Amount,
    /// The open positions.
    #[serde(default)]
    pub positions: Vec<Position>,
    /// `total_notional`
    pub total_notional: Amount,
}

/// A public trade, with nothing that identifies the parties.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FuturesPublicTrade {
    /// `price`
    pub price: Amount,
    /// `buy` or `sell`: the taker's side.
    pub side: String,
    /// `size`
    pub size: Amount,
    /// When, unix milliseconds.
    pub time: i64,
}

/// A public trade.
///
/// Deliberately anonymous: no account identifiers, and no indication of which side was the resting order beyond the aggressor direction.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PublicTrade {
    /// Trade id.
    pub id: String,
    /// `price`
    pub price: Amount,
    /// `quantity`
    pub quantity: Amount,
    /// Gapless per-market sequence.
    pub sequence: i64,
    /// `side`
    pub side: OrderSide,
    /// When it executed.
    pub timestamp: DateTime<Utc>,
}

/// The server's clock.
///
/// Two-factor codes are time-based, so a client can compare its own clock against this before a skewed clock gets a correct code rejected.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ServerTime {
    /// Current time in milliseconds since the Unix epoch.
    pub epoch_ms: i64,
    /// Current time as RFC 3339 with an explicit UTC offset.
    pub iso: String,
}

open_enum! {
    /// Sort direction for a paginated listing.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    SortDirection {
        Asc => "asc",
        Desc => "desc",
    }
}

/// A sub-account.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SubAccount {
    /// Always `false`. A sub-account has no withdrawal path — stated explicitly so a client does not have to infer it.
    pub can_withdraw: bool,
    /// When it was created.
    pub created_at: DateTime<Utc>,
    /// Opaque identifier. Use it to transfer funds and to issue API keys.
    pub id: String,
    /// Whether it may trade.
    pub is_active: bool,
    /// The label given at creation.
    pub label: String,
}

open_enum! {
    /// How long an order remains eligible to match.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    TimeInForce {
        Gtc => "gtc",
        Ioc => "ioc",
        Fok => "fok",
        PostOnly => "post_only",
    }
}

/// Unique identifier of a trade.
pub type TradeId = String;

open_enum! {
    /// Which way the price must move for a stop to fire.
    ///
    /// Explicit rather than inferred from the side, because the inference is ambiguous: a sell stop below the market is a stop-loss, and a sell stop above it is a take-profit. Both are legitimate, and guessing wrong means an order that fires at exactly the wrong moment — which is the one thing a protective order must never do.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    TriggerDirection {
        Above => "above",
        Below => "below",
    }
}

/// Unique identifier of a user account.
pub type UserId = String;

/// A saved withdrawal address.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WithdrawalAddress {
    /// The address.
    pub address: String,
    /// Asset, when restricted to one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    /// When it was saved.
    pub created_at: DateTime<Utc>,
    /// Address-book entry id.
    pub id: String,
    /// Your label.
    pub label: String,
    /// When it was last withdrawn to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<DateTime<Utc>>,
    /// Memo, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    /// Network code.
    pub network: String,
    /// Whether ownership has been confirmed.
    pub verified: bool,
}

/// One transition in a withdrawal's life.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WithdrawalHistoryEntry {
    /// When.
    pub at: DateTime<Utc>,
    /// Why, where a reason applies.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// `status`
    pub status: WithdrawalStatus,
}

/// Unique identifier of a withdrawal.
pub type WithdrawalId = String;

/// A withdrawal.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Withdrawal {
    /// Destination.
    pub address: String,
    /// `amount`
    pub amount: Amount,
    /// Asset symbol.
    pub asset: String,
    /// When it was broadcast.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub broadcast_at: Option<DateTime<Utc>>,
    /// Whether the account holder may still cancel it.
    pub cancellable: bool,
    /// When it confirmed to the required depth.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    /// Confirmations observed.
    pub confirmations: i32,
    /// When it was requested.
    pub created_at: DateTime<Utc>,
    /// Explorer link, when available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub explorer_url: Option<String>,
    /// `fee`
    pub fee: Amount,
    /// Asset the fee was charged in.
    pub fee_asset: String,
    /// Transitions this withdrawal has been through.
    #[serde(default)]
    pub history: Vec<WithdrawalHistoryEntry>,
    /// Withdrawal id.
    pub id: String,
    /// Memo, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    /// Network code.
    pub network: String,
    /// `status`
    pub status: WithdrawalStatus,
    /// Transaction hash, once broadcast.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
}

open_enum! {
    /// Lifecycle of an outgoing withdrawal.
    ///
    ///
    ///
    /// `pending_approval` waits for an operator to approve the withdrawal. `broadcast_unknown`
    /// means the transaction may have been sent: the funds stay debited until it is resolved
    /// against the chain.
    ///
    /// The type is open: values added to the API later decode as `Other`.
    WithdrawalStatus {
        Requested => "requested",
        PendingApproval => "pending_approval",
        Approved => "approved",
        Processing => "processing",
        Broadcast => "broadcast",
        Completed => "completed",
        Rejected => "rejected",
        Cancelled => "cancelled",
        Failed => "failed",
        BroadcastUnknown => "broadcast_unknown",
        Reverted => "reverted",
    }
}
