// Code generated by tools/generate.py from cexy-api-spec; DO NOT EDIT.

//! The SDK surface (operation table) and query-parameter structs, generated from the
//! shared OpenAPI document.

#![allow(clippy::doc_markdown)]

use chrono::{DateTime, SecondsFormat, Utc};

use crate::models_gen::*;

/// The `info.version` of the SDK spec this crate was generated from.
pub const SPEC_VERSION: &str = "1.0.0";

/// One operation of the SDK surface.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[non_exhaustive]
pub enum OperationId {
    /// `cancel_all`
    CancelAll,
    /// `cancel_order`
    CancelOrder,
    /// `deposit_address`
    DepositAddress,
    /// `exchange_config`
    ExchangeConfig,
    /// `exit_pool`
    ExitPool,
    /// `export_deposits`
    ExportDeposits,
    /// `export_ledger`
    ExportLedger,
    /// `export_orders`
    ExportOrders,
    /// `export_trades`
    ExportTrades,
    /// `export_withdrawals`
    ExportWithdrawals,
    /// `get_asset`
    GetAsset,
    /// `get_balance`
    GetBalance,
    /// `get_candles`
    GetCandles,
    /// `get_deposit`
    GetDeposit,
    /// `get_ledger`
    GetLedger,
    /// `get_market`
    GetMarket,
    /// `get_market_trades`
    GetMarketTrades,
    /// `get_order`
    GetOrder,
    /// `get_order_book`
    GetOrderBook,
    /// `get_order_by_client_id`
    GetOrderByClientId,
    /// `get_pool`
    GetPool,
    /// `get_withdrawal`
    GetWithdrawal,
    /// `join_pool`
    JoinPool,
    /// `list_api_keys`
    ListApiKeys,
    /// `list_assets`
    ListAssets,
    /// `list_balances`
    ListBalances,
    /// `list_deposits`
    ListDeposits,
    /// `list_fee_schedules`
    ListFeeSchedules,
    /// `list_markets`
    ListMarkets,
    /// `list_networks`
    ListNetworks,
    /// `list_notifications`
    ListNotifications,
    /// `list_open_orders`
    ListOpenOrders,
    /// `list_pools`
    ListPools,
    /// `list_sub_accounts`
    ListSubAccounts,
    /// `list_withdrawal_addresses`
    ListWithdrawalAddresses,
    /// `list_withdrawals`
    ListWithdrawals,
    /// `order_history`
    OrderHistory,
    /// `place_order`
    PlaceOrder,
    /// `server_time`
    ServerTime,
    /// `sub_account_balances`
    SubAccountBalances,
    /// `trade_history`
    TradeHistory,
}

/// Method, path, authentication and required API-key scope of an operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OperationInfo {
    /// HTTP method, upper case.
    pub method: &'static str,
    /// Path template, such as `/api/v1/markets/{symbol}`.
    pub path: &'static str,
    /// `"none"` or `"api_key"`.
    pub auth: &'static str,
    /// `""`, `"read"` or `"trade"`.
    pub scope: &'static str,
}

impl OperationId {
    /// Every operation of the SDK surface (41).
    pub const ALL: [OperationId; 41] = [
        OperationId::CancelAll,
        OperationId::CancelOrder,
        OperationId::DepositAddress,
        OperationId::ExchangeConfig,
        OperationId::ExitPool,
        OperationId::ExportDeposits,
        OperationId::ExportLedger,
        OperationId::ExportOrders,
        OperationId::ExportTrades,
        OperationId::ExportWithdrawals,
        OperationId::GetAsset,
        OperationId::GetBalance,
        OperationId::GetCandles,
        OperationId::GetDeposit,
        OperationId::GetLedger,
        OperationId::GetMarket,
        OperationId::GetMarketTrades,
        OperationId::GetOrder,
        OperationId::GetOrderBook,
        OperationId::GetOrderByClientId,
        OperationId::GetPool,
        OperationId::GetWithdrawal,
        OperationId::JoinPool,
        OperationId::ListApiKeys,
        OperationId::ListAssets,
        OperationId::ListBalances,
        OperationId::ListDeposits,
        OperationId::ListFeeSchedules,
        OperationId::ListMarkets,
        OperationId::ListNetworks,
        OperationId::ListNotifications,
        OperationId::ListOpenOrders,
        OperationId::ListPools,
        OperationId::ListSubAccounts,
        OperationId::ListWithdrawalAddresses,
        OperationId::ListWithdrawals,
        OperationId::OrderHistory,
        OperationId::PlaceOrder,
        OperationId::ServerTime,
        OperationId::SubAccountBalances,
        OperationId::TradeHistory,
    ];

    /// The API's operationId, such as `"place_order"`.
    pub fn as_str(self) -> &'static str {
        match self {
            OperationId::CancelAll => "cancel_all",
            OperationId::CancelOrder => "cancel_order",
            OperationId::DepositAddress => "deposit_address",
            OperationId::ExchangeConfig => "exchange_config",
            OperationId::ExitPool => "exit_pool",
            OperationId::ExportDeposits => "export_deposits",
            OperationId::ExportLedger => "export_ledger",
            OperationId::ExportOrders => "export_orders",
            OperationId::ExportTrades => "export_trades",
            OperationId::ExportWithdrawals => "export_withdrawals",
            OperationId::GetAsset => "get_asset",
            OperationId::GetBalance => "get_balance",
            OperationId::GetCandles => "get_candles",
            OperationId::GetDeposit => "get_deposit",
            OperationId::GetLedger => "get_ledger",
            OperationId::GetMarket => "get_market",
            OperationId::GetMarketTrades => "get_market_trades",
            OperationId::GetOrder => "get_order",
            OperationId::GetOrderBook => "get_order_book",
            OperationId::GetOrderByClientId => "get_order_by_client_id",
            OperationId::GetPool => "get_pool",
            OperationId::GetWithdrawal => "get_withdrawal",
            OperationId::JoinPool => "join_pool",
            OperationId::ListApiKeys => "list_api_keys",
            OperationId::ListAssets => "list_assets",
            OperationId::ListBalances => "list_balances",
            OperationId::ListDeposits => "list_deposits",
            OperationId::ListFeeSchedules => "list_fee_schedules",
            OperationId::ListMarkets => "list_markets",
            OperationId::ListNetworks => "list_networks",
            OperationId::ListNotifications => "list_notifications",
            OperationId::ListOpenOrders => "list_open_orders",
            OperationId::ListPools => "list_pools",
            OperationId::ListSubAccounts => "list_sub_accounts",
            OperationId::ListWithdrawalAddresses => "list_withdrawal_addresses",
            OperationId::ListWithdrawals => "list_withdrawals",
            OperationId::OrderHistory => "order_history",
            OperationId::PlaceOrder => "place_order",
            OperationId::ServerTime => "server_time",
            OperationId::SubAccountBalances => "sub_account_balances",
            OperationId::TradeHistory => "trade_history",
        }
    }

    /// Method, path, authentication and scope.
    pub fn info(self) -> OperationInfo {
        match self {
            OperationId::CancelAll => OperationInfo {
                method: "POST",
                path: "/api/v1/trading/orders/cancel-all",
                auth: "api_key",
                scope: "trade",
            },
            OperationId::CancelOrder => OperationInfo {
                method: "DELETE",
                path: "/api/v1/trading/orders/{order_id}",
                auth: "api_key",
                scope: "trade",
            },
            OperationId::DepositAddress => OperationInfo {
                method: "GET",
                path: "/api/v1/wallet/deposit-address",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ExchangeConfig => OperationInfo {
                method: "GET",
                path: "/api/v1/config",
                auth: "none",
                scope: "",
            },
            OperationId::ExitPool => OperationInfo {
                method: "POST",
                path: "/api/v1/pools/{symbol}/exit",
                auth: "api_key",
                scope: "trade",
            },
            OperationId::ExportDeposits => OperationInfo {
                method: "GET",
                path: "/api/v1/exports/deposits",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ExportLedger => OperationInfo {
                method: "GET",
                path: "/api/v1/exports/ledger",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ExportOrders => OperationInfo {
                method: "GET",
                path: "/api/v1/exports/orders",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ExportTrades => OperationInfo {
                method: "GET",
                path: "/api/v1/exports/trades",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ExportWithdrawals => OperationInfo {
                method: "GET",
                path: "/api/v1/exports/withdrawals",
                auth: "api_key",
                scope: "read",
            },
            OperationId::GetAsset => OperationInfo {
                method: "GET",
                path: "/api/v1/assets/{symbol}",
                auth: "none",
                scope: "",
            },
            OperationId::GetBalance => OperationInfo {
                method: "GET",
                path: "/api/v1/account/balances/{asset}",
                auth: "api_key",
                scope: "read",
            },
            OperationId::GetCandles => OperationInfo {
                method: "GET",
                path: "/api/v1/markets/{symbol}/candles",
                auth: "none",
                scope: "",
            },
            OperationId::GetDeposit => OperationInfo {
                method: "GET",
                path: "/api/v1/wallet/deposits/{deposit_id}",
                auth: "api_key",
                scope: "read",
            },
            OperationId::GetLedger => OperationInfo {
                method: "GET",
                path: "/api/v1/account/ledger",
                auth: "api_key",
                scope: "read",
            },
            OperationId::GetMarket => OperationInfo {
                method: "GET",
                path: "/api/v1/markets/{symbol}",
                auth: "none",
                scope: "",
            },
            OperationId::GetMarketTrades => OperationInfo {
                method: "GET",
                path: "/api/v1/markets/{symbol}/trades",
                auth: "none",
                scope: "",
            },
            OperationId::GetOrder => OperationInfo {
                method: "GET",
                path: "/api/v1/trading/orders/{order_id}",
                auth: "api_key",
                scope: "read",
            },
            OperationId::GetOrderBook => OperationInfo {
                method: "GET",
                path: "/api/v1/markets/{symbol}/orderbook",
                auth: "none",
                scope: "",
            },
            OperationId::GetOrderByClientId => OperationInfo {
                method: "GET",
                path: "/api/v1/trading/orders/by-client-id/{client_order_id}",
                auth: "api_key",
                scope: "read",
            },
            OperationId::GetPool => OperationInfo {
                method: "GET",
                path: "/api/v1/pools/{symbol}",
                auth: "none",
                scope: "",
            },
            OperationId::GetWithdrawal => OperationInfo {
                method: "GET",
                path: "/api/v1/wallet/withdrawals/{withdrawal_id}",
                auth: "api_key",
                scope: "read",
            },
            OperationId::JoinPool => OperationInfo {
                method: "POST",
                path: "/api/v1/pools/{symbol}/join",
                auth: "api_key",
                scope: "trade",
            },
            OperationId::ListApiKeys => OperationInfo {
                method: "GET",
                path: "/api/v1/account/api-keys",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ListAssets => OperationInfo {
                method: "GET",
                path: "/api/v1/assets",
                auth: "none",
                scope: "",
            },
            OperationId::ListBalances => OperationInfo {
                method: "GET",
                path: "/api/v1/account/balances",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ListDeposits => OperationInfo {
                method: "GET",
                path: "/api/v1/wallet/deposits",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ListFeeSchedules => OperationInfo {
                method: "GET",
                path: "/api/v1/fees",
                auth: "none",
                scope: "",
            },
            OperationId::ListMarkets => OperationInfo {
                method: "GET",
                path: "/api/v1/markets",
                auth: "none",
                scope: "",
            },
            OperationId::ListNetworks => OperationInfo {
                method: "GET",
                path: "/api/v1/networks",
                auth: "none",
                scope: "",
            },
            OperationId::ListNotifications => OperationInfo {
                method: "GET",
                path: "/api/v1/account/notifications",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ListOpenOrders => OperationInfo {
                method: "GET",
                path: "/api/v1/trading/orders",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ListPools => OperationInfo {
                method: "GET",
                path: "/api/v1/pools",
                auth: "none",
                scope: "",
            },
            OperationId::ListSubAccounts => OperationInfo {
                method: "GET",
                path: "/api/v1/account/sub-accounts",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ListWithdrawalAddresses => OperationInfo {
                method: "GET",
                path: "/api/v1/wallet/withdrawal-addresses",
                auth: "api_key",
                scope: "read",
            },
            OperationId::ListWithdrawals => OperationInfo {
                method: "GET",
                path: "/api/v1/wallet/withdrawals",
                auth: "api_key",
                scope: "read",
            },
            OperationId::OrderHistory => OperationInfo {
                method: "GET",
                path: "/api/v1/trading/orders/history",
                auth: "api_key",
                scope: "read",
            },
            OperationId::PlaceOrder => OperationInfo {
                method: "POST",
                path: "/api/v1/trading/orders",
                auth: "api_key",
                scope: "trade",
            },
            OperationId::ServerTime => OperationInfo {
                method: "GET",
                path: "/api/v1/time",
                auth: "none",
                scope: "",
            },
            OperationId::SubAccountBalances => OperationInfo {
                method: "GET",
                path: "/api/v1/account/sub-accounts/{id}/balances",
                auth: "api_key",
                scope: "read",
            },
            OperationId::TradeHistory => OperationInfo {
                method: "GET",
                path: "/api/v1/trading/trades",
                auth: "api_key",
                scope: "read",
            },
        }
    }
}

/// Query parameters of `deposit_address`. `None` is not sent.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DepositAddressParams {
    /// Asset symbol.
    ///
    /// Required.
    pub asset: String,
    /// Network code.
    ///
    /// Required.
    pub network: String,
}

impl DepositAddressParams {
    /// Parameters with the required values; the optional ones are unset.
    pub fn new(asset: impl Into<String>, network: impl Into<String>) -> Self {
        Self {
            asset: asset.into(),
            network: network.into(),
        }
    }

    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        {
            let v = &self.asset;
            q.push(("asset", v.clone()));
        }
        {
            let v = &self.network;
            q.push(("network", v.clone()));
        }
        q
    }
}

/// Query parameters of `export_deposits`, `export_ledger`, `export_orders`, `export_trades`, `export_withdrawals`. `None` is not sent.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ExportParams {
    /// Start of the period, inclusive. Defaults to 30 days ago.
    pub from: Option<DateTime<Utc>>,
    /// End of the period, inclusive. Defaults to now.
    pub to: Option<DateTime<Utc>>,
}

impl ExportParams {
    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        if let Some(v) = &self.from {
            q.push(("from", v.to_rfc3339_opts(SecondsFormat::AutoSi, true)));
        }
        if let Some(v) = &self.to {
            q.push(("to", v.to_rfc3339_opts(SecondsFormat::AutoSi, true)));
        }
        q
    }
}

/// Query parameters of `get_candles`. `None` is not sent.
#[derive(Debug, Clone, PartialEq)]
pub struct GetCandlesParams {
    /// Bucket width.
    ///
    /// Required.
    pub interval: CandleInterval,
    /// Earliest bucket to return.
    pub start_time: Option<DateTime<Utc>>,
    /// Latest bucket to return.
    pub end_time: Option<DateTime<Utc>>,
    /// Maximum buckets. Capped server-side.
    pub limit: Option<i32>,
}

impl GetCandlesParams {
    /// Parameters with the required values; the optional ones are unset.
    pub fn new(interval: CandleInterval) -> Self {
        Self {
            interval,
            start_time: None,
            end_time: None,
            limit: None,
        }
    }

    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        {
            let v = &self.interval;
            q.push(("interval", v.as_str().to_string()));
        }
        if let Some(v) = &self.start_time {
            q.push(("start_time", v.to_rfc3339_opts(SecondsFormat::AutoSi, true)));
        }
        if let Some(v) = &self.end_time {
            q.push(("end_time", v.to_rfc3339_opts(SecondsFormat::AutoSi, true)));
        }
        if let Some(v) = &self.limit {
            q.push(("limit", v.to_string()));
        }
        q
    }
}

/// Query parameters of `get_ledger`. `None` is not sent.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetLedgerParams {
    /// Limit to one asset.
    pub asset: Option<String>,
    /// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
    pub cursor: Option<String>,
    /// Maximum items to return. Clamped to `MAX_LIMIT`.
    pub limit: Option<i32>,
    /// Sort direction. Defaults to newest-first.
    pub direction: Option<SortDirection>,
}

impl GetLedgerParams {
    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        if let Some(v) = &self.asset {
            q.push(("asset", v.clone()));
        }
        if let Some(v) = &self.cursor {
            q.push(("cursor", v.clone()));
        }
        if let Some(v) = &self.limit {
            q.push(("limit", v.to_string()));
        }
        if let Some(v) = &self.direction {
            q.push(("direction", v.as_str().to_string()));
        }
        q
    }
}

/// Query parameters of `get_market_trades`. `None` is not sent.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetMarketTradesParams {
    /// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
    pub cursor: Option<String>,
    /// Maximum items to return. Clamped to `MAX_LIMIT`.
    pub limit: Option<i32>,
    /// Sort direction. Defaults to newest-first.
    pub direction: Option<SortDirection>,
}

impl GetMarketTradesParams {
    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        if let Some(v) = &self.cursor {
            q.push(("cursor", v.clone()));
        }
        if let Some(v) = &self.limit {
            q.push(("limit", v.to_string()));
        }
        if let Some(v) = &self.direction {
            q.push(("direction", v.as_str().to_string()));
        }
        q
    }
}

/// Query parameters of `get_order_book`. `None` is not sent.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetOrderBookParams {
    /// Price levels per side. Capped server-side.
    pub depth: Option<i64>,
}

impl GetOrderBookParams {
    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        if let Some(v) = &self.depth {
            q.push(("depth", v.to_string()));
        }
        q
    }
}

/// Query parameters of `list_deposits`. `None` is not sent.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListDepositsParams {
    /// Limit to one asset.
    pub asset: Option<String>,
    /// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
    pub cursor: Option<String>,
    /// Maximum items to return. Clamped to `MAX_LIMIT`.
    pub limit: Option<i32>,
    /// Sort direction. Defaults to newest-first.
    pub direction: Option<SortDirection>,
}

impl ListDepositsParams {
    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        if let Some(v) = &self.asset {
            q.push(("asset", v.clone()));
        }
        if let Some(v) = &self.cursor {
            q.push(("cursor", v.clone()));
        }
        if let Some(v) = &self.limit {
            q.push(("limit", v.to_string()));
        }
        if let Some(v) = &self.direction {
            q.push(("direction", v.as_str().to_string()));
        }
        q
    }
}

/// Query parameters of `list_notifications`. `None` is not sent.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListNotificationsParams {
    /// Return only notices that have not been read.
    pub unread_only: Option<bool>,
    /// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
    pub cursor: Option<String>,
    /// Maximum items to return. Clamped to `MAX_LIMIT`.
    pub limit: Option<i32>,
    /// Sort direction. Defaults to newest-first.
    pub direction: Option<SortDirection>,
}

impl ListNotificationsParams {
    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        if let Some(v) = &self.unread_only {
            q.push(("unread_only", v.to_string()));
        }
        if let Some(v) = &self.cursor {
            q.push(("cursor", v.clone()));
        }
        if let Some(v) = &self.limit {
            q.push(("limit", v.to_string()));
        }
        if let Some(v) = &self.direction {
            q.push(("direction", v.as_str().to_string()));
        }
        q
    }
}

/// Query parameters of `list_open_orders`. `None` is not sent.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListOpenOrdersParams {
    /// Limit to one market.
    pub symbol: Option<String>,
    /// Limit to one status.
    pub status: Option<OrderStatus>,
}

impl ListOpenOrdersParams {
    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        if let Some(v) = &self.symbol {
            q.push(("symbol", v.clone()));
        }
        if let Some(v) = &self.status {
            q.push(("status", v.as_str().to_string()));
        }
        q
    }
}

/// Query parameters of `list_withdrawals`. `None` is not sent.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ListWithdrawalsParams {
    /// Limit to one asset.
    pub asset: Option<String>,
    /// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
    pub cursor: Option<String>,
    /// Maximum items to return. Clamped to `MAX_LIMIT`.
    pub limit: Option<i32>,
    /// Sort direction. Defaults to newest-first.
    pub direction: Option<SortDirection>,
}

impl ListWithdrawalsParams {
    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        if let Some(v) = &self.asset {
            q.push(("asset", v.clone()));
        }
        if let Some(v) = &self.cursor {
            q.push(("cursor", v.clone()));
        }
        if let Some(v) = &self.limit {
            q.push(("limit", v.to_string()));
        }
        if let Some(v) = &self.direction {
            q.push(("direction", v.as_str().to_string()));
        }
        q
    }
}

/// Query parameters of `order_history`. `None` is not sent.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct OrderHistoryParams {
    /// Limit to one market.
    pub symbol: Option<String>,
    /// Limit to one status.
    pub status: Option<OrderStatus>,
    /// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
    pub cursor: Option<String>,
    /// Maximum items to return. Clamped to `MAX_LIMIT`.
    pub limit: Option<i32>,
    /// Sort direction. Defaults to newest-first.
    pub direction: Option<SortDirection>,
}

impl OrderHistoryParams {
    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        if let Some(v) = &self.symbol {
            q.push(("symbol", v.clone()));
        }
        if let Some(v) = &self.status {
            q.push(("status", v.as_str().to_string()));
        }
        if let Some(v) = &self.cursor {
            q.push(("cursor", v.clone()));
        }
        if let Some(v) = &self.limit {
            q.push(("limit", v.to_string()));
        }
        if let Some(v) = &self.direction {
            q.push(("direction", v.as_str().to_string()));
        }
        q
    }
}

/// Query parameters of `trade_history`. `None` is not sent.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TradeHistoryParams {
    /// Limit to one market.
    pub symbol: Option<String>,
    /// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
    pub cursor: Option<String>,
    /// Maximum items to return. Clamped to `MAX_LIMIT`.
    pub limit: Option<i32>,
    /// Sort direction. Defaults to newest-first.
    pub direction: Option<SortDirection>,
}

impl TradeHistoryParams {
    pub(crate) fn query(&self) -> Vec<(&'static str, String)> {
        let mut q = Vec::new();
        if let Some(v) = &self.symbol {
            q.push(("symbol", v.clone()));
        }
        if let Some(v) = &self.cursor {
            q.push(("cursor", v.clone()));
        }
        if let Some(v) = &self.limit {
            q.push(("limit", v.to_string()));
        }
        if let Some(v) = &self.direction {
            q.push(("direction", v.as_str().to_string()));
        }
        q
    }
}
